-- 01_inventory.sql — assessment-only (assess). Reads state for the evidence loop.
SET DEFINE OFF
SET FEEDBACK OFF
WHENEVER SQLERROR CONTINUE

PROMPT === profiles ===
SELECT PROFILE, RESOURCE_NAME, LIMIT
FROM   DBA_PROFILES
WHERE  RESOURCE_NAME IN ('FAILED_LOGIN_ATTEMPTS','PASSWORD_LIFE_TIME',
                         'PASSWORD_LOCK_TIME','PASSWORD_REUSE_MAX','INACTIVE_ACCOUNT_TIME')
ORDER  BY PROFILE, RESOURCE_NAME;

PROMPT === open (non-locked) accounts ===
SELECT USERNAME, ACCOUNT_STATUS, PROFILE
FROM   DBA_USERS
WHERE  ACCOUNT_STATUS = 'OPEN'
ORDER  BY USERNAME;

PROMPT === unified auditing enabled? ===
SELECT VALUE AS unified_auditing
FROM   V$OPTION
WHERE  PARAMETER = 'Unified Auditing';

PROMPT === enabled unified audit policies ===
SELECT POLICY_NAME, ENABLED_OPTION
FROM   AUDIT_UNIFIED_ENABLED_POLICIES
ORDER  BY POLICY_NAME;
